name: Build bcdice-js

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '2.7'
          bundler-cache: true
          cache-version: 0
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '14'
          cache: 'npm'

      - name: Build
        run: |
          bundle install
          npm install
          npm run build

      - name: Deploy to Branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          mkdir ../temp_build
          cp -r examples lib ts LICENSE README.md package.json ../temp_build/

          git checkout -B dist
          find . -maxdepth 1 ! -name '.git' ! -name '..' ! -name '.' -exec rm -rf {} +

          cp -r ../temp_build/* .
          git add .

          git commit -m "Auto-deploy build results" || echo "Nothing to commit"
          git push origin dist --force